#!/bin/bash

BRANCH=$1
# introspecting version by running the built image
THUMBOR_VERSION=`docker run --rm minimalcompact/thumbor bash -c "pip freeze |grep ^thumbor== | cut -d= -f 3"`
echo "THUMBOR VERSION: $THUMBOR_VERSION"

echo "--> pushing minimalcompact/thumbor:simdsse4"
[ "$BRANCH" == "master" ] && docker push minimalcompact/thumbor:latest-simd-sse4
docker push minimalcompact/thumbor:$THUMBOR_VERSION-simd-sse4

echo "--> pushing minimalcompact/thumbor:simdavx2"
[ "$BRANCH" == "master" ] && docker push minimalcompact/thumbor:latest-simd-avx2
docker push minimalcompact/thumbor:$THUMBOR_VERSION-simd-avx2

echo "--> pushing minimalcompact/thumbor-nginx-proxy (DEPRECATED)"
[ "$BRANCH" == "master" ] && docker push minimalcompact/thumbor-nginx-proxy:latest
docker push minimalcompact/thumbor-nginx-proxy:$THUMBOR_VERSION

echo "--> pushing minimalcompact/thumbor-nginx-proxy-cache"
[ "$BRANCH" == "master" ] && docker push minimalcompact/thumbor-nginx-proxy-cache:latest
docker push minimalcompact/thumbor-nginx-proxy-cache:$THUMBOR_VERSION

echo "--> pushing minimalcompact/remotecv"
[ "$BRANCH" == "master" ] && docker push minimalcompact/remotecv:latest
docker push minimalcompact/remotecv:$THUMBOR_VERSION

echo "--> pushing minimalcompact/thumbor"
[ "$BRANCH" == "master" ] && docker push minimalcompact/thumbor:latest
docker push minimalcompact/thumbor:$THUMBOR_VERSION
