version: "3"
services:
  thumbor:
    image: minimalcompact/thumbor
    environment:
      # we can control the number of processes and threads via ENV
      - THUMBOR_NUM_PROCESSES=${THUMBOR_NUM_PROCESSES:-1}
      - ENGINE_THREADPOOL_SIZE=${ENGINE_THREADPOOL_SIZE:-0}
      # no result storage / caching, so we measure thumbor's processing
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_STORES_UNSAFE=True
      # keeping loader storage, to make tests more consistent
      # (eliminate time to fetch external images)
      - STORAGE=thumbor.storages.file_storage
    volumes:
      # mounting a /data folder to store cached images
      - ./data:/data
  imagor:
    image: shumc/imagor:0.6.4
    environment:
      # we can control the number of processes and threads via ENV
      - VIPS_CONCURRENCY_LEVEL=${THUMBOR_NUM_PROCESSES:-1}
      - IMAGOR_UNSAFE=1
      # no result storage / caching, so we measure imagor's processing
      # keeping loader storage, to make tests more consistent
      # (eliminate time to fetch external images)
      - FILE_LOADER_BASE_DIR=/mnt/data
      - FILE_STORAGE_BASE_DIR=/mnt/data
    volumes:
      # mounting a /data folder to store cached images
      - ./data_imagor:/data
  # This is the master locust engine
  locust:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - THUMBOR_DOCKER_PROCS=${THUMBOR_DOCKER_PROCS:-1}
      - THUMBOR_NUM_PROCESSES=${THUMBOR_NUM_PROCESSES:-1}
      - ENGINE_THREADPOOL_SIZE=${ENGINE_THREADPOOL_SIZE:-0}
    volumes:
      - ./scripts:/opt/scripts
      - ./reports:/opt/reports
    command: "locust
              --host=http://${TEST_HOST}
              -f /opt/scripts/benchmark.py
              --headless
              -u 200
              -r 4
              --run-time 2m
              --master
              --expect-workers 3
              --only-summary
              --csv=/opt/reports/${TEST_HOST}/${THUMBOR_DOCKER_PROCS}-${THUMBOR_NUM_PROCESSES}"
  # this is the locust slave. We can control the number of slaves using docker-compose scale
  locust-slave:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/opt/scripts
      - ./reports:/opt/reports
    command: "locust
              --host=http://${TEST_HOST}
              -f /opt/scripts/benchmark.py
              --headless
              --worker
              --master-host=locust"
